version: "3"

services:
  server:
    container_name: server
    build: ./server
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    command: bash -c "python manage.py runserver 0.0.0.0:$SERVER_PORT"
    working_dir: /app/server/
    volumes:
      - ./server:/app/server
    environment:
      - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
    env_file:
      - .env

  database:
    image: mysql:8.0
    container_name: ${DATABASE_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "$DATABASE_PORT:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  client:
    container_name: client
    build: ./client
    ports:
      - "$CLIENT_PORT:$CLIENT_PORT"
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_GRAPHQL_ENDPOINT=${REACT_APP_GRAPHQL_ENDPOINT}
